# Generated by Django 6.0.2 on 2026-02-24 16:38

import django.db.models.deletion
import usage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_used', models.IntegerField(default=0)),
                ('messages_limit', models.IntegerField(default=100)),
                ('reset_date', models.DateField(default=usage.models.get_default_reset_date)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso',
                'verbose_name_plural': 'Usos',
            },
        ),
    ]
